server:
  port: 8080


app:
  ai:
    work-dir: C:/jpyrust_temp
    source-script-dir: d:/JPyRust/python-core
    model-path: "yolov8n.pt"
    confidence: 0.5

logging:
  level:
    root: INFO
    com.jpyrust: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
